Update test-poc.yml

diff --git a/.github/workflows/test-poc.yml b/.github/workflows/test-poc.yml
--- a/.github/workflows/test-poc.yml
+++ b/.github/workflows/test-poc.yml
@@ -14,11 +14,18 @@ jobs:
 
       - name: List all repositories
         env:
-          GITHUB_TOKEN: ${{ github.token }} 
+          GITHUB_TOKEN: ${{ github.token }}
         run: |
-          curl -s -H "Authorization: token $GITHUB_TOKEN" \
-          https://api.github.com/user/repos?per_page=100 \
-          | jq -r '.[] | .name' > repo_list.txt
+          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+          https://api.github.com/user/repos?per_page=100)
+
+          # Check if the response is valid JSON
+          if echo "$response" | jq empty; then
+            echo "$response" | jq -r '.[] | .name' > repo_list.txt
+          else
+            echo "Failed to retrieve repositories: $response"
+            exit 1  # Exit if the response is not valid JSON
+          fi
 
       - name: Check if Tomer created the repo and it’s not a fork
         env:
@@ -32,7 +39,7 @@ jobs:
             owner=$(echo "$repo_info" | jq -r '.owner.login')
             creator=$(echo "$repo_info" | jq -r '.owner.type')
             fork=$(echo "$repo_info" | jq -r '.fork')
-              
+
             if [ "$owner" == "$TOMER_USERNAME" ] && [ "$creator" == "User" ] && [ "$fork" == "false" ]; then
               echo "Tomer created $repo and it is not a fork"
             else
